[package]
name = "bc-components"
version = "0.10.0"
edition = "2021"
description = "Secure Components for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-components-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["cryptography"]
documentation = "https://docs.rs/bc-components"

[dependencies]
# bc-crypto = { path = "../bc-crypto" }
bc-crypto = "0.3"

bc-rand = "0.1"

# dcbor = { path = "../dcbor" }
dcbor = "0.13"

# bc-ur = { path = "../bc-ur" }
bc-ur = "0.3"

# sskr = { path = "../sskr" }
sskr = "0.3"

hex = "0.4.3"
miniz_oxide = "0.7.1"
paste = "1.0.12"
anyhow = "1.0"
url = "2.4.1"
bytes = "1.5.0"

[dev-dependencies]
hex-literal = "0.4.1"
indoc = "2.0.0"
version-sync = "0.9"
