[package]
name = "bc-components"
version = "0.12.2"
edition = "2021"
description = "Secure Components for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-components-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["cryptography"]
documentation = "https://docs.rs/bc-components"

[dependencies]
bc-crypto = "^0.5.0"
bc-rand = "^0.2.0"
dcbor = "^0.15.0"
bc-ur = "^0.5.0"
sskr = "^0.4.0"

hex = "^0.4.3"
miniz_oxide = "^0.7.1"
paste = "^1.0.12"
anyhow = "^1.0"
url = "^2.4.1"
ssh-key = { version = "=0.6.6", default-features = false, features = ["dsa", "ecdsa", "rand_core", "std", "crypto"] }
zeroize = { version = "1.8.1", default-features = false, features = ["alloc", "zeroize_derive"] }
rand_core = "0.6.4"
frost-secp256k1-tr = { git = "https://github.com/zebra-lucky/frost", rev = "d580241e8561ed145a464e6671a511d5a8c218f8" }

[dev-dependencies]
hex-literal = "^0.4.1"
indoc = "^2.0.0"
version-sync = "^0.9.0"
