[package]
name = "bc-components"
version = "0.1.0"
edition = "2021"
description = "Secure Components for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-components-rust"
readme = "README.md"
categories = ["cryptography"]
documentation = "https://docs.rs/bc-components"

[dependencies]
bc-crypto = { path = "../bc-crypto-rust" }
dcbor = "0.7.0"
bc-ur = { path = "../bc-ur-rust" }
sskr = { path = "../bc-sskr-rust" }
hex = "0.4.3"
miniz_oxide = "0.7.1"
paste = "1.0.12"

[dev-dependencies]
hex-literal = "0.4.1"
indoc = "2.0.0"
version-sync = "0.9"
